@echo off
echo Initializing Git...
git init
echo Setting branch to main...
git branch -M main
echo Adding remote origin...
git remote add origin "https://github.com/Reibinchacko/WattX.git" || git remote set-url origin "https://github.com/Reibinchacko/WattX.git"
echo Staging files...
git add .
echo Committing changes...
git commit -m "Expand database schema and add new models"
echo Pushing to GitHub...
git push -u origin main
echo Done.
